# Generated by Django 5.0.6 on 2024-06-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_annonceimage_annonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='conditions_colocations',
            field=models.ManyToManyField(blank=True, null=True, to='api.conditioncolocation'),
        ),
    ]
